# Generated by Django 3.2.3 on 2021-06-03 16:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import posts.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('images', '0002_postimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=150, unique=True)),
                ('title', models.CharField(max_length=120)),
                ('content', models.TextField()),
                ('status',
                 models.CharField(choices=[('S', 'SUBMITTED'), ('R', 'RETURNED'), ('P', 'PUBLISHED'), ('W', 'WRITING')],
                                  default='W', max_length=2)),
                ('thumbnail', models.ForeignKey(default=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                                to='images.postimage')),
                ('writer',
                 models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL,
                                   validators=[posts.models.validate_for_writer])),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publish', models.BooleanField(default=None, null=True)),
                ('review', models.TextField(blank=True, null=True)),
                ('post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='posts.post',
                                           validators=[posts.models.check_post_status])),
                ('reviewed_by',
                 models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewer',
                                   to=settings.AUTH_USER_MODEL, validators=[posts.models.validate_for_staff])),
                ('writer',
                 models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='author',
                                   to=settings.AUTH_USER_MODEL, validators=[posts.models.validate_for_writer])),
            ],
        ),
    ]
