# Generated by Django 3.2.3 on 2021-06-07 16:39

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):
    dependencies = [
        ('images', '0003_auto_20210607_2209'),
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='publish',
            new_name='approved',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='writer',
        ),
        migrations.AddField(
            model_name='post',
            name='last_edited',
            field=models.DateTimeField(auto_now_add=True,
                                       default=datetime.datetime(2021, 6, 7, 16, 39, 33, 181388, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('S', 'SUBMITTED'), ('D', 'DRAFT'), ('P', 'PUBLISHED')], default='W',
                                   max_length=2),
        ),
        migrations.AlterField(
            model_name='post',
            name='thumbnail',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT,
                                    to='images.postthumbnail'),
        ),
    ]
