# Generated by Django 3.2.3 on 2021-06-11 05:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('posts', '0002_auto_20210607_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('S', 'SUBMITTED'), ('D', 'DRAFT'), ('P', 'PUBLISHED')], default='D',
                                   max_length=2),
        ),
    ]
