# Generated by Django 3.2.3 on 2021-06-11 14:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('posts', '0003_alter_post_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='date_submitted',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
