# Generated by Django 3.2.3 on 2021-09-30 08:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('posts', '0005_post_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('S', 'SUBMITTED'), ('D', 'DRAFT'), ('P', 'PUBLISHED'), ('R', 'REJECTED')],
                                   default='D', max_length=2),
        ),
    ]
