# Generated by Django 3.2.3 on 2021-06-03 16:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(unique=True, upload_to='post-images')),
            ],
        ),
    ]
