# Generated by Django 3.2.3 on 2021-06-07 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('posts', '0001_initial'),
        ('images', '0002_postimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostThumbnail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default.jpg', unique=True, upload_to='thumbnails')),
            ],
        ),
        migrations.AddField(
            model_name='postimage',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='posts.post'),
        ),
    ]
